apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bar-alod-ch
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bar-alod-ch.zazuko.net
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: bar-alod-ch-cert
      hosts:
        - bar.alod.ch
  rules:
    - host: bar.alod.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: varnish
              servicePort: 80
