apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bar-alod-ch
resources:
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: bar-alod-ch

bases:
  - server
  - varnish
