apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2

  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: bar-alod-ch
          image: docker.io/zazuko/bar-alod-ch
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # This makes sure the pods are not all scheduled on the same node
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels: {}
                topologyKey: "kubernetes.io/hostname"
